"""
repoheal_fixes.py — Auto-generated compatibility shims for deprecated/removed APIs.
Generated by RepoHeal.

Import in your code and replace deprecated calls with repohealauto_* equivalents.
"""

# Auto-generated by RepoHeal for compatibility.

# Auto-generated by RepoHeal for compatibility.
