"""
repoheal_fixes.py — Auto-generated compatibility shims for deprecated/removed APIs.
Generated by RepoHeal.

Import in your code and replace deprecated calls with repohealauto_* equivalents.
"""

try:
    _repoheal_DataFrame_imported
except NameError:
    import pandas as _repoheal_pandas
    _repoheal_DataFrame_imported = True

def repohealauto_DataFrame(*args, **kwargs):
    """Compatibility shim: pandas.DataFrame — forwards to original pandas.DataFrame.
    This API is deprecated. The shim preserves old-code behavior.
    Replace calls to 'DataFrame()' with 'repohealauto_DataFrame()'.
    """
    return _repoheal_pandas.DataFrame(*args, **kwargs)

try:
    _repoheal_describe_imported
except NameError:
    import pandas as _repoheal_pandas
    _repoheal_describe_imported = True

def repohealauto_describe(*args, **kwargs):
    """Compatibility shim: pandas.describe — forwards to original pandas.describe.
    This API is deprecated. The shim preserves old-code behavior.
    Replace calls to 'describe()' with 'repohealauto_describe()'.
    """
    return _repoheal_pandas.describe(*args, **kwargs)

try:
    _repoheal_array_imported
except NameError:
    import numpy as _repoheal_numpy
    _repoheal_array_imported = True

def repohealauto_array(*args, **kwargs):
    """Compatibility shim: numpy.array — forwards to original numpy.array.
    This API is deprecated. The shim preserves old-code behavior.
    Replace calls to 'array()' with 'repohealauto_array()'.
    """
    return _repoheal_numpy.array(*args, **kwargs)

try:
    _repoheal_item_imported
except NameError:
    import numpy as _repoheal_numpy
    _repoheal_item_imported = True

def repohealauto_item(*args, **kwargs):
    """Compatibility shim: numpy.item — forwards to original numpy.item.
    This API is deprecated. The shim preserves old-code behavior.
    Replace calls to 'item()' with 'repohealauto_item()'.
    """
    return _repoheal_numpy.item(*args, **kwargs)

try:
    _repoheal_get_imported
except NameError:
    import requests as _repoheal_requests
    _repoheal_get_imported = True

def repohealauto_get(*args, **kwargs):
    """Compatibility shim: requests.get — forwards to original requests.get.
    This API is deprecated. The shim preserves old-code behavior.
    Replace calls to 'get()' with 'repohealauto_get()'.
    """
    return _repoheal_requests.get(*args, **kwargs)


# 5 shim(s) generated.
